CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  guid TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL DEFAULT '',
  about TEXT NOT NULL DEFAULT '',
  password TEXT NULL,
  name TEXT NOT NULL,
  gender TEXT NOT NULL,
  date_of_birth TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS youtube_channels (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  external_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  tags TEXT [] NOT NULL DEFAULT '{}',
  active BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS youtube_videos (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  youtube_channel_id BIGINT NOT NULL,

  external_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  tags TEXT [] NOT NULL DEFAULT '{}',
  active BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_youtube_channel_id FOREIGN KEY (youtube_channel_id) REFERENCES youtube_channels(id)
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS worksheets (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  title TEXT NOT NULL,
  image_url TEXT NOT NULL
);
ALTER SEQUENCE worksheets_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS worksheet_contents (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  worksheet_id BIGINT NOT NULL,

  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,

  CONSTRAINT fk_worksheet_id FOREIGN KEY (worksheet_id) REFERENCES worksheets(id)
);
ALTER SEQUENCE worksheet_contents_id_seq RESTART WITH 1;
