CREATE EXTENSION citext;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  guid TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  about TEXT NOT NULL DEFAULT '',
  password TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  photo_url TEXT NOT NULL DEFAULT '',
  user_role TEXT NOT NULL DEFAULT 'basic',
  username CITEXT NOT NULL UNIQUE
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS youtube_channels (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  external_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  tags TEXT [] NOT NULL DEFAULT '{}',
  channel_link TEXT NOT NULL DEFAULT '#',
  active BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS youtube_videos (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  youtube_channel_id BIGINT NOT NULL,

  external_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  tags TEXT [] NOT NULL DEFAULT '{}',
  active BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_youtube_channel_id FOREIGN KEY (youtube_channel_id) REFERENCES youtube_channels(id)
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS worksheets (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  title TEXT NOT NULL,
  cover_file_guid TEXT NOT NULL
);
ALTER SEQUENCE worksheets_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS worksheet_contents (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  worksheet_id BIGINT NOT NULL,

  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_file_guid TEXT NOT NULL,

  CONSTRAINT fk_worksheet_id FOREIGN KEY (worksheet_id) REFERENCES worksheets(id)
);
ALTER SEQUENCE worksheet_contents_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS books (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  cover_file_guid TEXT NOT NULL,
  tags TEXT [] NOT NULL DEFAULT '{}',
  type TEXT NOT NULL DEFAULT 'default',
  pdf_file_guid TEXT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  original_pdf_url TEXT NULL
);
ALTER SEQUENCE books_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS book_contents (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  book_id BIGINT NOT NULL,

  page_number BIGINT NOT NULL,
  description TEXT NOT NULL,
  image_file_guid TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',

  CONSTRAINT fk_book_id FOREIGN KEY (book_id) REFERENCES books(id)
);
ALTER SEQUENCE book_contents_id_seq RESTART WITH 1;
ALTER TABLE books
  ADD storage TEXT NOT NULL DEFAULT 'local',
  ADD access_tags TEXT [] NOT NULL DEFAULT '{free}';

CREATE TABLE IF NOT EXISTS file_bucket (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  guid TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  base_type TEXT NOT NULL,
  extension TEXT NOT NULL,
  http_content_type TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  data BYTEA,
  exact_path TEXT
);
ALTER SEQUENCE file_bucket_id_seq RESTART WITH 1;
ALTER TABLE file_bucket
  ADD storage TEXT NOT NULL DEFAULT 'local',
  ADD size_kb BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  user_id BIGINT NOT NULL,

  number TEXT NOT NULL UNIQUE,
  order_type TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'initialized',
  payment_status TEXT NOT NULL DEFAULT 'initialized',
  base_price BIGINT NOT NULL DEFAULT 0,
  price BIGINT NOT NULL DEFAULT 0,
  discount_amount BIGINT NOT NULL DEFAULT 0,
  final_price BIGINT NOT NULL DEFAULT 0,
  payment_number TEXT UNIQUE,
  metadata JSONB NOT NULL DEFAULT '{}',

  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);
ALTER SEQUENCE orders_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,
  expired_at TIMESTAMP WITH TIME ZONE,
  success_at TIMESTAMP WITH TIME ZONE,

  order_number TEXT NOT NULL UNIQUE,
  number TEXT NOT NULL UNIQUE,
  payment_platform TEXT NOT NULL,
  payment_type TEXT NOT NULL,
  status TEXT NOT NULL,
  reference_status TEXT,
  reference_number TEXT UNIQUE,
  fraud_status TEXT,
  masked_card TEXT,
  amount BIGINT NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}'
);
ALTER SEQUENCE payments_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  code TEXT NOT NULL UNIQUE,
  benefit_type TEXT NOT NULL,
  name TEXT NOT NULL,
  image_url TEXT NOT NULL,
  base_price BIGINT NOT NULL,
  price BIGINT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'
);
ALTER SEQUENCE products_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS user_subscriptions (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  user_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,

  product_code TEXT NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_order_id FOREIGN KEY (order_id) REFERENCES orders(id)
);
ALTER SEQUENCE user_subscriptions_id_seq RESTART WITH 1;
