package payment_lib

const (
	STATUS_INITIALIZED = "initialized"
	STATUS_SUCCESS     = "success"
	STATUS_PENDING     = "pending"
	STATUS_FAILED      = "failed"
	STATUS_CANCELED    = "canceled"
	STATUS_EXPIRED     = "expired"
	STATUS_REFUNDED    = "refunded"

	PAYMENT_PLATFORM_MIDTRANS = "midtrans"

	PAYMENT_TYPE_MIDTRANS = "midtrans"
	PAYMENT_TYPE_GOPAY    = "gopay"
	PAYMENT_TYPE_QRIS     = "qris"

	MIDTRANS_STATUS_CAPTURE        = "capture"
	MIDTRANS_STATUS_SETTLEMENT     = "settlement"
	MIDTRANS_STATUS_PENDING        = "pending"
	MIDTRANS_STATUS_DENY           = "deny"
	MIDTRANS_STATUS_CANCEL         = "cancel"
	MIDTRANS_STATUS_EXPIRE         = "expire"
	MIDTRANS_STATUS_FAILURE        = "failure"
	MIDTRANS_STATUS_REFUND         = "refund"
	MIDTRANS_STATUS_PARTIAL_REFUND = "partial_refund"
	MIDTRANS_STATUS_AUTHORIZE      = "authorize"

	FRAUD_STATUS_ACCEPT = "accept"
	FRAUD_STATUS_DENY   = "deny"
)

var (
	MIDTRANS_STATUS_TO_SUCCESS  = []string{MIDTRANS_STATUS_CAPTURE, MIDTRANS_STATUS_SETTLEMENT}
	MIDTRANS_STATUS_TO_PENDING  = []string{MIDTRANS_STATUS_PENDING}
	MIDTRANS_STATUS_TO_FAILED   = []string{MIDTRANS_STATUS_DENY, MIDTRANS_STATUS_FAILURE}
	MIDTRANS_STATUS_TO_CANCELED = []string{MIDTRANS_STATUS_CANCEL}
	MIDTRANS_STATUS_TO_EXPIRED  = []string{MIDTRANS_STATUS_EXPIRE}
	MIDTRANS_STATUS_TO_REFUNDED = []string{MIDTRANS_STATUS_REFUND, MIDTRANS_STATUS_PARTIAL_REFUND}
)
